data{
	int<lower=0>N;//numberofdatapointsinentiredataset
	int<lower=0>K;//numberofmixturecomponents
	int<lower=0>D;//dimension
	vector[D]y[N];//observations
	real<lower=0>alpha0;//dirichletprior
	real<lower=0>mu_sigma0;//meansprior
	real<lower=0>sigma_sigma0;//variancesprior
}
transformeddata{
	vector<lower=0>[K]alpha0_vec;
	for(kin1:K){
		alpha0_vec[k]<-alpha0;
	}
}
parameters{
	simplex[K]theta;//mixingproportions
	vector[D]mu[K];//locationsofmixturecomponents
	vector<lower=0>[D]sigma[K];//standarddeviationsofmixturecomponents
}
model{
	//priors
	theta~dirichlet(alpha0_vec);
	for(kin1:K){
		mu[k]~normal(0.0,mu_sigma0);
		sigma[k]~lognormal(0.0,sigma_sigma0);
	}
	//likelihood
	for(nin1:N){
		realps[K];
		for(kin1:K){
			ps[k]<-log(theta[k])+normal_log(y[n],mu[k],sigma[k]);
		}
		increment_log_prob(log_sum_exp(ps));
	}
}
